### ISSUE TITLE
aeproject-lib in package.json is not updated with --update

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aeproject#283]

**Comment by HristiyanG** [comment]
Hey @thepiwo ,

your issue has been resolved in the latest version @2.1.0 of**aeproject**.

**Comment by thepiwo** [comment]
@HristiyanG still happened for me with the update from 2.0.1 to 2.1.0

**Comment by marc0olo** [comment]
cleaning up old issues. feel free to re-open if still relevant
